"""add foreign key to Review

Revision ID: 71210903c2e4
Revises: 94e9e2f3c9d2
Create Date: 2026-01-06 12:03:30.841563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71210903c2e4'
down_revision = '94e9e2f3c9d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_reviews_employee_id_employees'), 'reviews', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_employee_id_employees'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'employee_id')
    # ### end Alembic commands ###
